# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Get submodules
submodules:
  include: all
  recursive: true

# Set the version of Python and other tools you might need
build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  jobs:
    pre_build:
      - mkdir -p docs/source/examples
      - |
        for f in data/notebooks/*; do
          b=$(basename $f)
          if [ ! -f "docs/source/examples/$b" ]; then
            ln -s -t docs/source/examples "../../../$f"
          fi
        done
    post_build:
      - ls -l
      - ls -l _readthedocs/html
      - ls -l docs
  apt_packages:
    - graphviz
    - libopenblas-dev

# Build documentation in the docs/ directory with Sphinx
sphinx:
   builder: html
   configuration: docs/source/conf.py
   fail_on_warning: false

# Declare the Python requirements required to build your docs
python:
   install:
   - requirements: docs/docs_requirements.txt
   - requirements: docs/rtd_requirements.txt
